[package]
name = "json"
version = "0.12.0"
authors = ["Maciej Hirsz <maciej.hirsz@gmail.com>"]
description = "JSON implementation in Rust"
repository = "https://github.com/maciejhirsz/json-rust"
documentation = "http://json.rs/doc/json/"
license = "MIT/Apache-2.0"

[dev-dependencies]
# serde = "*"
# serde_json = "*"
# serde_macros = "*"
# rustc-serialize = "*"
# num-traits = "*"
